name: SonarQube Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean install -DskipTests
          mvn sonar:sonar \
            -Dsonar.projectKey=user-management \
            -Dsonar.projectName=User-Management \
            -Dsonar.projectVersion=0.0.1-SNAPSHOT \
            -Dsonar.host.url=http://54.165.64.243:9000 \
            -Dsonar.login=${SONAR_TOKEN}
